# File created for PythonLesson2.py
# All contents are explained there.

input()
input('Text')
print(input())
print('Hello, my name is ' + input())
Example = input('Your name: ')
print('Hello ' + Example + ', I am Jason. Nice to meet you!')
input('You: ').capitalize()
input('You: ').upper()
input('You: ').lower()
input('You: ').replace('Alex', 'Jason')
print(input('You: ').split(' '))
input('Bot: Hello!\nYou: ')
name = input('Bot: What is your name? I am Jason.\nYou: ')
input("Bot: Cool, nice to meet you {0}. How's your day?".format(name))
input('This is a sentence, and you will be able to send input below this sentence\n')
input('This is a sentence, but you won\'t be able to give input.')
print("Didn't you said, \"Yes, I will do my homework\"?")